### PR TITLE
OPENTOK-43278: Replace Android samples bintray links with Maven Central links

### PR DESCRIPTION
**Pull request by jintgeorge**
Replace Android samples bintray links with Maven Central links.

### CODE REVIEW

**Review by rperezcubero — APPROVED** [review]

**Comment by igorwojda** [comment]
I think jCenter is part of Bintray, so we should remove `jCenter()` repos:
 
_To streamline the productivity of the JFrog Platform we will be sunsetting Bintray (including JCenter), GoCenter, and ChartCenter services on May 1st, 2021._

**Comment by v-kpheng** [comment]
> It looks like JCenter is part of Bintray, so we should remove `jCenter()` repos:
> 
> _To streamline the productivity of the JFrog Platform we will be sunsetting Bintray (including JCenter), GoCenter, and ChartCenter services on May 1st, 2021._

Thanks, @igorwojda.  Good catch!

@jintgeorge, can you please update and test again please?  Thanks!

**Comment by jintgeorge** [comment]
@igorwojda Can you please review again?

**Comment by v-kpheng** [comment]
@jintgeorge, can we still remove `jcenter`?  I thought the plan was to leave it in place?

(Because without it, our sample apps won't compile because of the missing dependences)

Please advise.  Thanks!

**Comment by v-kpheng** [comment]
> @jintgeorge, can we still remove `jcenter`? I thought the plan was to leave it in place?
> 
> (Because without it, our sample apps won't compile because of the missing dependences)
> 
> Please advise. Thanks!

@jintgeorge, please advise.  ☝️ Thanks!

**Comment by jintgeorge** [comment]
@v-kpheng We are not removing jcenter completely from our sample apps. The ones removed are only for opentok-android-sdk which have been already migrated to Maven Central.

**Comment by jintgeorge** [comment]
@igorwojda Can you review this again please?

**Comment by igorwojda** [comment]
Looks good - I am merging this now.

BTW @v-kpheng samples are guarded by various CI checks running with each PR (via Github actions) - each app is built and over 200 Unit tests run to verify various consistency aspects across all samples.

**Comment by jintgeorge** [comment]
Thanks @igorwojda

**Pull request merged**
