### PR TITLE
Impelimeted TextureView in CustomVideo Renderer

### PR DESCRIPTION
**Pull request by avirepo**
We face a problem with the SurfaceView in provided renderer, so after spending time figure out what can be a better solution to replace the SurfaceView with TextureView.

In this code we have implemented OTTextureView which will be handle by OTTextureRenderer and the top most interface it OTVideoRenderer which basically implement BaseRenderer of open tok and pass event to OTTextureRenderer.

The implementation is improve video rendering performance drastically and we can now also have animation on video view as currently it is TextureView.

The implementation won't be possible without help of "https://github.com/romannurik/muzei" refer the GLTextureView from there and change the code as per our project requirement.

Hope the solution will be helpful for other android developers who are using the OpenTok solution in their app.

### CODE REVIEW

**Comment by avirepo** [comment]
Hey, I hope the solution is helpful for your clients like me.

**Comment by avirepo** [comment]
Hey, I hope solution will be helpful for your clients like me. Please provide an update here.

**Comment by tarasbilinsky** [comment]
I had problems original opentok's sample on resolutions other than 640x480:
-  when flipping device orientation and changing renderer dimensions, a strange stripes appear in rendered video
- when capturing frame shots getting a deadlock

Tried this implementation hoping it might fix these problems but it doesn't unfortunately

**Comment by avirepo** [comment]
On which device you are using the sample?

**Comment by avirepo** [comment]
For capturing the frame shots you need to move your code of capturing image from view in background thread else it will create a ANR.

**Comment by tarasbilinsky** [comment]
Moto Z 2016, but I guess it is device independent, it must be something in opentok's renderer code that breaks it when dimensions change from portrait to landscape.

**Comment by avirepo** [comment]
Please try with applying this
```
<activity
    android:name=".MainActivity"
    android:configChanges="orientation|screenSize">
</activity>
```
once hope it will work.

**Comment by tarasbilinsky** [comment]
android:configChanges="orientation|screenSize" is already there

**Comment by robjperez** [comment]
There is a way to enable TextureViews instead of SurfaceView inside the SDK.

When building the `Session`, you need to provide a subclass of https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.SessionOptions.html overriding the method `useTextureViews` to return `true`

When doing this, `publisher.getView()` will return a TextureView instead of a GLSurfaceView

**Pull request closed without merging**
