### PR TITLE
OPENTOK-40557 Add custom video capturer sample app using camera2 interface

### PR DESCRIPTION
**Pull request by jintgeorge**
[OPENTOK-40557](https://tokbox.atlassian.net/browse/OPENTOK-40557)

### CODE REVIEW

**Comment by msach22** [comment]
@jintgeorge Could you please add a README similar to the other applications?

**Comment by jintgeorge** [comment]
retest this please

**Comment by robjperez** [comment]
Thanks for working on this @jintgeorge 
I think the sample should have its own folder at the root of the samples repo.
The idea behind the samples was to offer stand alone applications.

Something like this
```
Archiving
Basic-Video-Chat
Custom-Audio-Driver
Custom-Video-Driver
Custom-Capturer-Camera2
FrameMetadata
...
```

The actual Camera2 Capturer can be placed inside the CustomVideoDriverLib, as in this other sample:

https://github.com/opentok/opentok-android-sdk-samples/blob/master/FrameMetadata/settings.gradle

What do you think?

**Comment by jintgeorge** [comment]
> Thanks for working on this @jintgeorge
> I think the sample should have its own folder at the root of the samples repo.
> The idea behind the samples was to offer stand alone applications.
> 
> Something like this
> 
> ```
> Archiving
> Basic-Video-Chat
> Custom-Audio-Driver
> Custom-Video-Driver
> Custom-Capturer-Camera2
> FrameMetadata
> ...
> ```
> 
> The actual Camera2 Capturer can be placed inside the CustomVideoDriverLib, as in this other sample:
> 
> https://github.com/opentok/opentok-android-sdk-samples/blob/master/FrameMetadata/settings.gradle
> 
> What do you think?

@robjperez I will move it to a stand alone app.

**Comment by jintgeorge** [comment]
Closing this PR as opening another one with different changes.

**Pull request closed without merging**
