### PR TITLE
Android Sample: vp9 stride value fix

### PR DESCRIPTION
**Pull request by IGitGotIt**
vp9 subscriber frames were not being rendered properly.

### CODE REVIEW

**Review by goncalocostamendes — CHANGES_REQUESTED** [review]
Live-Photo-Capture-Kotlin is failing to build. Seems to be related with your changes.

**Review by jintgeorge — APPROVED** [review]
LGTM

**Review by goncalocostamendes — APPROVED** [review]
+1

**Review by jintgeorge — APPROVED** [review]
+1

**Pull request merged**
